server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  #ignore services
  #after:http://myzuul.com:9527/microservicecloud-dept/dept/get/2 can't get service
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept
#setting route
#before:http://myzuul.com:9527/microservicecloud-dept/dept/get/2
#after:http://myzuul.com:9527/mydept/dept/get/1